config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    collection do
      get :feeds
      get :ranking
    end

    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end

    resources :comments, only: [:create, :destroy]
  end


  resources :categories, only: :show
  
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  # 如果分類下已有餐廳，就不允許刪除分類（刪除時拋出 Error）
  has_many :restaurants, dependent: :restrict_with_error

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }

  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :friend_id, uniqueness: { scope: :user_id }

  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant, counter_cache: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category, optional: true
  # 當 Restaurant 物件被刪除時，順便刪除依賴的 Comment
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def prev
    Restaurant.where("id<?", id).last    
  end

  def next
    Restaurant.where("id>?", id).first
  end

  def is_favorited?(user)
    self.favorited_users.include?(user)    
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  def count_favor
    self.favor_count = self.favorites.size
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader
  
  # 如果 User 已經有了評論，就不允許刪除帳號（刪除時拋出 Error）
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :adding_mes, through: :inverse_friendships, source: :user

  def friend?(user)
    self.friends.include?(user) || self.adding_mes.include?(user)
  end

  def admin?
    self.role == "admin"    
  end

  def following?(user)
    self.followings.include?(user)    
  end

  def all_friends
    friends = self.friends + self.adding_mes
    return friends.uniq
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  protected

  # Devise 客製化屬性的使用說明：  https://github.com/plataformatec/devise#strong-parameters

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])    
  end


  
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to restaurant_path(@restaurant)
    else
      flash[:alert] = "Comments can't be blank!"
      redirect_back(fallback_location: request.referrer)
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin? || current_user == @comment.user
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    def edit
      unless @user==current_user
        redirect_to user_path(@user)
      end
    end

    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers
  end
 

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def friend_list
    @friends = current_user.all_friends
  end

  private

  def set_user
    @user = User.find(params[:id])      
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gourmetsmap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Belleza" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>


      <!-- 導覽列 -->
      <%= render partial: "shared/navbar" %>

      <% if flash[:notice] %>

        <div class="alert alert-success alert-dismissible" role="alert">
          <button class="close" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <strong><%= notice %></strong>
        </div>

      <% end %>

      <% if flash[:alert] %>

        <div class="alert alert-warning alert-dismissible" role="alert">
          <button class="close" type="button" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <strong><%= alert %></strong>
        </div>

      <% end %>
    
    <div id="bg">
      <%= image_tag "console-background.jpg" %>
    </div>
    <%= yield %>
    
  </body>
</html>

app/views/shared/_favorite.html.erb
<div class="favor-btn">
  <% if restaurant.is_favorited?(current_user) %>
    <%= link_to unfavorite_restaurant_path(restaurant), method: :post do %>
      <i class="fas fa-heart fa-lg"><%= restaurant.favor_count %></i>
    <% end %>
  <% else %>
    <%= link_to favorite_restaurant_path(restaurant), method: :post do %>
      <i class="far fa-heart fa-lg"><%= restaurant.favor_count %></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user) %>
    <%= link_to 'UnFollow', followship_path(user), method: :delete, class: "btn btn-warning btn-sm" %>
  <% else %>
    <%= link_to 'Follow', followships_path(following_id: user), method: :post, class: "btn btn-success btn-sm" %>
  <% end %>
<% end %>

app/views/shared/_friend-btn.html.erb
<% if user != current_user %>
  <% if current_user.friend?(user) %>
    <%= link_to 'x Friend', friendship_path(user), method: :delete, class: "btn btn-danger btn-sm" %>
  <% else %>
    <%= link_to '+ Friend', friendships_path(friend_id: user), method: :post, class: "btn btn-info btn-sm" %>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
<div class="favor-btn">
  <% if restaurant.is_liked?(current_user) %>
    <%= link_to unlike_restaurant_path(restaurant), method: :post do %>
      <i class="fas fa-thumbs-up fa-lg"><%= restaurant.likes_count %></i>
    <% end %>
  <% else %>
    <%= link_to like_restaurant_path(restaurant), method: :post do %>
      <i class="far fa-thumbs-up fa-lg"><%= restaurant.likes_count %></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <strong><%= link_to "Gourmets' Map", root_path, class: "navbar-brand" %></strong>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="pull-right text-right nav navbar-nav">
    <!-- 以下靠右 icons -->
      <% if current_user %>
        
        <li><%= link_to 'News Feeds', feeds_restaurants_path %></li>
        <li><%= link_to 'Top 10!', ranking_restaurants_path %></li>
        <li><%= link_to 'Gourmets Online', users_path %></li>

        <li class="dropdown">
          <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user-circle fa-lg"></i>
            Hi, <%=  current_user.name %>
            <span class="caret"></span>
          </a>

          <ul class="dropdown-menu dropdown-font" aria-labelledby="dropdownMenuLink">

            <li><%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            <li><%= link_to 'Front Desk', root_path %></li>

            <% if current_user.admin? %>
            <li>
              <%= link_to 'Console Room', admin_restaurants_path, class: "dropdown-item" %>
            </li>
            <% end %>

          </ul>
        </li>

        <li>
          <%= link_to edit_user_registration_path, title: "Change Password" do %>
          <%= icon('fas', 'cog', class: 'fa-lg') %>
          <% end %>
        </li>

      <% else %>
        <li>
          <%= link_to new_user_registration_path, title: "Register!" do %>
          <i class="fas fa-registered fa-lg"></i>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path, title: "Log in!" do %>
          <i class="fas fa-sign-in-alt fa-lg"></i>
        <% end %>
        </li>


      <% end %>        
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>

app/views/shared/_restaurant_list.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= image_tag restaurant.image, class: "img-responsive center-block" %>
      <div class="caption">
        <div class="right">
          <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
          <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
        </div>
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-default"><%= restaurant.category.name %></p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
      </div>
      
    </div>
  </div>

<% end %>