config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    collection do
      get :feeds
      get :ranking
    end

    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end

    resources :comments, only: [:create, :destroy]
  end


  resources :categories, only: :show
  
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category, optional: true
  # 當 Restaurant 物件被刪除時，順便刪除依賴的 Comment
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def prev
    Restaurant.where("id<?", id).last    
  end

  def next
    Restaurant.where("id>?", id).first
  end

  def is_favorited?(user)
    self.favorited_users.include?(user)    
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  def count_favor
    self.favor_count = self.favorites.size
    self.save
  end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
 
 

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "A new pin has been put down."
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "Failed to nail the pin."
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "You've updated this pin info."
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "Failed to update."
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "You've just removed a gourmet pin!"
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hour, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end



end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  before_action :set_restaurant, except: [:index, :feeds, :ranking]


  def index
    @restaurants = Restaurant.order(:created_at).page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @comment = Comment.new
    @comments = @restaurant.comments.order(created_at: :desc)
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(15)
  end

  def dashboard
  end

  def favorite
    current_user.favorites.create(restaurant: @restaurant)
    @restaurant.count_favor
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    @restaurant.count_favor
    redirect_back(fallback_location: root_path)

  end

  def like
    current_user.likes.create(restaurant: @restaurant)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favor_count: :desc).limit(10)
  end

  

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here!</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>



<%= form_for [:admin, @restaurant] do |f| %>
  
  <div class="form-group">
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :name, "Name"%>
    <%= f.text_field :name, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :opening_hour, "Opening Hour"%>
    <%= f.text_field :opening_hour, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :tel, "Tel" %>
    <%= f.text_field :tel, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address, "Address" %>
    <%= f.text_field :address, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :image, "Restaurant Photo" %>
    <%= image_tag @restaurant.image, width: '200px' if @restaurant.image? %>
    <%= f.file_field :image %>
  </div>
    
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/restaurants/edit.html.erb
<div class="container">
  <h2>Edit Restaurant</h2>
  <div class="row">
    <div class="col-md-12">
      <div>
        <%= link_to '✪ Index', admin_restaurants_path, class: "btn btn-default" %> 
      </div>
      <hr>
      <div class="col-md-8 col-md-offset-2 overlay-bb word-wt">
        <div class="form-block">
          <%= render partial: "form" %>
        </div>
        
      </div>
    </div>

  </div>
</div>

app/views/admin/restaurants/index.html.erb
<div class="container">
  <h2>Gourmet Log</h2>
  <%= link_to admin_categories_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-arrow-right"></span> Category List
  <% end %>
  <div class="row">
    <div class="col-md-12">   
      <hr>
      <div class="text-center">
        <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-primary" %>
      </div><br>
      <div class="col-md-8 col-md-offset-2 overlay">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Category</th>
              <th>Restaurant</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
            <% @restaurants.each do |restaurant| %>
              <tr>
                <td scope="row"><%= restaurant.id %></td>
                <td><span class="label label-default"><%= restaurant.category.name %></span></td>
                <td>☞ 
                <%= link_to admin_restaurant_path(restaurant) do %>
                  <strong><%= restaurant.name %></strong>
                <% end %>
                </td>
                <td>
                  <%= link_to 'Edit', edit_admin_restaurant_path(restaurant), class: "btn btn-warning btn-xs" %>
                  <%= link_to 'Delete', admin_restaurant_path(restaurant), class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure?"} %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="text-center">
        <%= paginate @restaurants %>
      </div>  

    </div> 
  </div>
</div>

app/views/admin/restaurants/new.html.erb
<div class="container">
  <h2>New Restaurant</h2>
  <div class="row">
    <div class="col-md-12">
      <div>
        <%= link_to '✪ Index', admin_restaurants_path, class: "btn btn-default" %> 
      </div>
      <hr>
      <div class="col-md-8 col-md-offset-2 overlay">
        <div class="form-block">
          <%= render partial: "form" %>
        </div>
        
      </div>
    </div>

  </div>
</div>

app/views/admin/restaurants/show.html.erb
<div class="container">
  <h2>Delicacies</h2>
  <div class="row">
    <div class="col-md-12">
      <nav aria-label="...">
        <ul class="pager">
          <li><%= link_to "Prev", admin_restaurant_path(@restaurant.prev) if @restaurant.prev %></li>
          <li><%= link_to '✪ Index', admin_restaurants_path %></li>
          <li><%= link_to 'Next', admin_restaurant_path(@restaurant.next) if @restaurant.next %></li>
        </ul>
      </nav>
      <hr>

      <div class="col-md-offset-1 overlay-b">
        <div class="show-block text-center">
          <div class="show-name">
            <h2 class="word-wt"><%= @restaurant.name %></h2>
            <p class="label label-default"><%= @restaurant.category.name %></p>
          </div>
          <div>
            <%= link_to 'Edit', edit_admin_restaurant_path(@restaurant), class: "btn btn-warning btn-xs" %>
                  <%= link_to 'Delete', admin_restaurant_path(@restaurant), class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
          <p class="word-wt">--------------------------------------</br>
          Opening Hour: <%= @restaurant.opening_hour %><br>
          Tel: <%= @restaurant.tel%><br>
          Address: <%= @restaurant.address%><br>
          --------------------------------------</p>
          <p class="word-wt"><strong>Restaurant Photo:</strong></p>
          <%= image_tag @restaurant.image, width: '400px' %><br>
          <p class="word-wt"><br>------------------------------------------------</p>
          <div class= "word-wt show-block-des">
            <%= @restaurant.description %><br><br>
          </div>
        </div>
      </div>
      <hr>
      <nav aria-label="...">
          <ul class="pager">
            <li><%= link_to "← Older", admin_restaurant_path(@restaurant.prev) if @restaurant.prev %></li>
            <li><%= link_to 'Newer →', admin_restaurant_path(@restaurant.next), class: "pager-newer" if @restaurant.next  %></li>
          </ul>
      </nav>
      <br><br>

    </div>
    
  </div>
</div>