config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    collection do
      get :feeds
      get :ranking
    end

    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end

    resources :comments, only: [:create, :destroy]
  end


  resources :categories, only: :show
  
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category, optional: true
  # 當 Restaurant 物件被刪除時，順便刪除依賴的 Comment
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def prev
    Restaurant.where("id<?", id).last    
  end

  def next
    Restaurant.where("id>?", id).first
  end

  def is_favorited?(user)
    self.favorited_users.include?(user)    
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end

  def count_favor
    self.favor_count = self.favorites.size
    self.save
  end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
 
 

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "A new pin has been put down."
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "Failed to nail the pin."
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "You've updated this pin info."
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "Failed to update."
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "You've just removed a gourmet pin!"
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hour, :tel, :address, :description, :image, :category_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end



end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  before_action :set_restaurant, except: [:index, :feeds, :ranking]


  def index
    @restaurants = Restaurant.order(:created_at).page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @comment = Comment.new
    @comments = @restaurant.comments.order(created_at: :desc)
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(15)
  end

  def dashboard
  end

  def favorite
    current_user.favorites.create(restaurant: @restaurant)
    @restaurant.count_favor
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    @restaurant.count_favor
    redirect_back(fallback_location: root_path)

  end

  def like
    current_user.likes.create(restaurant: @restaurant)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    likes = Like.where(restaurant: @restaurant, user: current_user)
    likes.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favor_count: :desc).limit(10)
  end

  

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %>'s Dashboard</h1>
      <hr>
      <ul>
        <li>有 <%= @restaurant.comments.count %> 筆評論</li>
        <li>這家餐廳的平均價位為 $XXX</li>
        <li>有 XX 人收藏這家餐廳</li>
      </ul>

    </div>
  </div>
</div>

app/views/restaurants/feeds.html.erb
<div class="container overlay-a">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-6 feeds-box">
        <h3>New Pins</h3>
        <hr style= "border:2px solid #ed6d72">
        <% @recent_restaurants.each do |restaurant| %>
          <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
          <p><span class="badge badge-default"><%= restaurant.category.name %></span></p>
          <p><strong><%= restaurant.description %></strong></p>
          <em>﹤<%= time_ago_in_words(restaurant.created_at) %> ago﹥</em>
          <hr style="border:1px solid #666666">
        <% end %>
      </div>

      <div class="col-md-6 feeds-box">
        <h3>New Comments</h3>
        <hr style="border:2px solid #ed6d72">
        <% @recent_comments.each do |comment| %>
          <h3><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %></h3>
          <p><strong><%= comment.content %></strong></p>
          <i>by <%= link_to comment.user.name, user_path(comment.user) %></i>
          <hr style="border:1px solid #666666">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="overlay-a">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <ul class="nav nav-pills nav-pills-center">
          <li role="presentation" class="active"><%= link_to "All Restaurants", root_path %></li>
          <% @categories.each do |category| %>
            <li role="presentation" class="nav-list"><%= link_to category.name, category_path(category) %></li>
          <% end %>
        </ul>
        <hr>
        

        <%= render partial: "shared/restaurant_list" %>

      </div>

      <div class="text-center">
        <%= paginate @restaurants %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/ranking.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 font-shadow page-header">
      <h1>Top 10 Most Favorited</h1>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-10 col-md-offset-1">

      <% @restaurants.each do |restaurant| %>
        <div class="ranking-box overlay-r">
          <div class="col-md-3 col-xs-3">
            <%= link_to restaurant_path(restaurant) do %>
              <%= image_tag restaurant.image, class: "img-responsive center-block" %>
            <% end %>
          </div>

          <div class="col-md-9 col-xs-9 overlay">
            <h4>
              <%= restaurant.name %>
              <span><%= render partial: 'shared/favorite', locals: { restaurant: restaurant } %></span>
              </h4>
              <p><%= truncate(restaurant.description, length: 200) %></p>
              <%= link_to 'Show', restaurant_path(restaurant), class: "btn btn-primary" %>
          </div>

        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h2>Delicacies</h2>
  <div class="row">
    <div class="col-md-12">
      <nav aria-label="...">
        <ul class="pager">
          <li><%= link_to "Prev", restaurant_path(@restaurant.prev) if @restaurant.prev %></li>
          <li><%= link_to '✪ Index', restaurants_path %></li>
          <li><%= link_to 'Next', restaurant_path(@restaurant.next) if @restaurant.next %></li>
        </ul>
      </nav>
      <hr>
      
      <!---------  Show Section ------------->
      <div class="col-md-offset-1 overlay-b">
        <div class="show-block text-center">
          <div class="show-name">
            <h2 class="word-wt"><%= @restaurant.name %></h2>
            <p class="label label-default"><%= @restaurant.category.name %></p>
          </div>

          <div class="favorite_like">
            <%= render partial: "shared/favorite", locals: {restaurant: @restaurant} %>
            <%= render partial: "shared/like", locals: {restaurant: @restaurant} %>
          </div>
          
          <p class="word-wt">--------------------------------------<br><br>
          Opening Hour: <%= @restaurant.opening_hour %><br>
          Tel: <%= @restaurant.tel%><br>
          Address: <%= @restaurant.address%><br><br>
          --------------------------------------</p>
          
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-custom" data-toggle="modal" data-target="#exampleModalCenter">
            Dashboard
          </button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h1 class="modal-title" id="exampleModalLongTitle"><%= @restaurant.name %>'s Dashboard</h1>
                </div>
                <div class="modal-body">
                  <h4>有 <%= @restaurant.comments.count %> 筆評論</h4>
                  <h4>這家餐廳的平均價位為 $XXX</h4>
                  <h4>有 XX 人收藏這家餐廳</h4>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

          <br>
          <p class="word-wt"><strong>Restaurant Photo:</strong></p>
          <%= image_tag @restaurant.image, width: '400px' %><br>
          <p class="word-wt"><br>------------------------------------------------</p>

          <div class= "word-wt show-block-des">
            <%= @restaurant.description %><br><br>
          </div>

        </div>

        <hr>
        
        <!----------- Comment Section ------------>
        <div class="show-comment">
          <%= form_for [@restaurant, @comment] do |f| %>
            <div class="form-group">
              <%= f.text_area :content, placeholder: "Leave your comments?", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.submit class: "btn" %>
              <%= f.button "Cancel", type: :reset, class: "btn" %>
            </div>
          <% end %>
        </div>
        <!---------- Show Comments Section --------->

        <% @comments.each do |comment| %>
        <div class="comment-block">
          <h4><%= comment.user.name %></h4>
          <p><%= simple_format comment.content %></p>
          <p class="text-muted">
            <em><%= time_ago_in_words(comment.created_at) %> ago -</em>
            <%= link_to 'Delete', restaurant_comment_path(@restaurant, comment), method: :delete, data: {confirm: "Are you sure?"} if current_user.admin? || current_user == comment.user %>
          </p>
        </div>
        <% end %>

      </div>
      <hr>
      <nav aria-label="...">
          <ul class="pager">
            <li><%= link_to "← Older", restaurant_path(@restaurant.prev) if @restaurant.prev %></li>
            <li><%= link_to 'Newer →', restaurant_path(@restaurant.next), class: "pager-newer" if @restaurant.next  %></li>
          </ul>
      </nav>
      <br><br>

    </div>
    
  </div>
</div>