config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    collection do
      get :feeds
      get :ranking
    end

    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end

    resources :comments, only: [:create, :destroy]
  end


  resources :categories, only: :show
  
  resources :users, only: [:show, :edit, :update, :index] do
    member do
      get :friend_list
    end
  end
  
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  # 如果分類下已有餐廳，就不允許刪除分類（刪除時拋出 Error）
  has_many :restaurants, dependent: :restrict_with_error

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  
  
  before_action :set_category, only: [:update, :destroy]

  def index
    @categories = Category.all

    if params[:id]
      @category = Category.find(params[:id])
    else
      @category = Category.new
    end
  end

  def update
    
    if @category.update(category_params)
      redirect_to admin_categories_path
      flash[:notice] = "Updated suscessfully!"
    else
      @categories = Category.all
      render :index
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "A new category is suscessfully created!"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end   
  end

  def destroy
    
    @category.destroy
    flash[:alert] = "You've deleted category #{@category.name}!"
    redirect_to admin_categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  <h2>Category List</h2>
  <%= link_to admin_restaurants_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Gourmet Log
  <% end %>
  <div class="row">
    <div class="col-md-12">   
      <hr>

      
        <div class="form-inline text-center">
          <%= form_for [:admin, @category] do |f| %>
            <div class="form-group">
              <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
            </div>
            <%= f.submit class: "btn btn-primary" %>
            <%= link_to 'Cancel', admin_categories_path, class: "btn btn-danger" if @category.name.present? %>
          <% end %>
        </div>
        
        <div class="cg-alert-o">
          <% if @category.errors.any? %>
            <div class="cg-alert text-center">
              <b><%= @category.errors.full_messages.to_sentence %></b>
            </div>
          <% end %>
        </div>
        

      <div class="col-md-8 col-md-offset-2 overlay">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Category</th>
              <th>Options</th>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
            <tr>
              <th scope="row"><%= category.id %></th>
              <td><span class="label label-default"><%= category.name %></span></td>
              <td>
                <%= link_to 'Edit', admin_categories_path(id: category.id), class: "btn btn-warning btn-xs" %>
                <%= link_to 'Delete', admin_category_path(category), class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure?"} %>                  
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div> 

    </div> 
  </div>
</div>